services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9091:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
    restart: always