services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9091:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    user: root

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3001:3000'
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    user: root

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9101:9100